"""add unique constraint for tenant idempotency key

Revision ID: 869f1571eea9
Revises: 43d97ca46bd9
Create Date: 2026-08-13 21:12:29.546025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869f1571eea9'
down_revision: Union[str, Sequence[str], None] = '43d97ca46bd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_events_tenant_idempotency_key'), 'events', type_='unique')
    op.create_index('ix_events_tenant_idempotency', 'events', ['tenant_id', 'idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_events_tenant_idempotency', table_name='events')
    op.create_unique_constraint(op.f('uq_events_tenant_idempotency_key'), 'events', ['tenant_id', 'idempotency_key'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
