"""add event aggregates

Revision ID: c6694750d5d3
Revises: eaf1bf2d3151
Create Date: 2026-08-12 15:54:42.759524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6694750d5d3'
down_revision: Union[str, Sequence[str], None] = 'eaf1bf2d3151'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_aggregates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('event_name', sa.String(length=255), nullable=False),
    sa.Column('time_bucket', sa.DateTime(timezone=True), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_aggregates_tenant_event_bucket', 'event_aggregates', ['tenant_id', 'event_name', 'time_bucket'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_aggregates_tenant_event_bucket', table_name='event_aggregates')
    op.drop_table('event_aggregates')
    # ### end Alembic commands ###
